INSERT INTO hotels(name, description, photo_url, price_per_night)
VALUES
('Costa del Sol Resort', 'Resort de lujo frente al mar con spa, tres restaurantes y actividades acuáticas', 'https://static.leonardo-hotels.com/image/leonardohotelbucharestcitycenter_room_comfortdouble2_2022_4000x2600_7e18f254bc75491965d36cc312e8111f_1200x780_mobile_3.webp', 449.99),
('Hotel Campo Verde', 'Hotel tranquilo en el campo con vistas a la montaña, ideal para escapadas románticas', 'https://static.leonardo-hotels.com/image/P_LHBLR_05_may16_4000x2600_8254e8943e796f7d44a32ffd8d650a25_1200x780_mobile_3.webp', 99.89),
('Urbano Moderno', 'Hotel boutique en el centro de la ciudad con decoración moderna y un bar en la azotea', 'https://static.leonardo-hotels.com/image/p_lrhbf_02_nov21_-4000x2600_0039400c1259e6b7fe1a79ef368294b9_1200x780_mobile_3.webp', 199.20),
('Refugio de Montaña', 'Hotel en la montaña con acceso a senderos de trekking y vistas panorámicas', 'https://www.estiber.com/blog/wp-content/uploads/2023/07/refugio-lluis-estasen.jpg', 37.99),
('Hotel del Sol', 'Disfruta del sol y la playa en nuestro resort', 'src/assets/img/foto10.jpg', 170.00),
('Hotel Azul', 'Un lugar tranquilo con vista al mar', 'src/assets/img/foto1.jpg', 120.50),
('Hotel Estrella', 'Un refugio elegante en el centro de la ciudad', 'src/assets/img/foto2.jpg', 89.99),
('Hotel del Bosque', 'Experimenta la naturaleza en nuestro acogedor hotel', 'src/assets/img/foto3.jpg', 150.25),
('Hotel de Montaña', 'Disfruta de la serenidad en las alturas', 'src/assets/img/foto4.jpg', 110.00),
('Hotel Elegante', 'Lujo y comodidad en cada rincón', 'src/assets/img/foto5.jpg', 200.75),
('Hotel Sereno', 'Un lugar de paz y relajación', 'src/assets/img/foto6.jpg', 95.50),
('Hotel Dorado', 'Experimenta la opulencia en nuestro hotel de cinco estrellas', 'src/assets/img/foto7.jpg', 180.00),
('Hotel Cielo', 'Vistas impresionantes desde las alturas', 'src/assets/img/foto8.jpg', 135.25),
('Hotel Encanto', 'Descubre la magia en nuestro hotel boutique', 'src/assets/img/foto9.jpg', 120.90),
('Hotel del Sol', 'Disfruta del sol y la playa en nuestro resort', 'src/assets/img/foto10.jpg', 170.00),
('Apartamento Sereno', 'Un apartamento acogedor para una estancia tranquila', 'src/assets/img/foto11.jpg', 75.50),
('Resort Oasis', 'Sumérgete en la relajación total en nuestro resort de lujo', 'src/assets/img/foto12.jpg', 220.00),
('Casa Rural Encantada', 'Experimenta la autenticidad en nuestra casa rural histórica', 'src/assets/img/foto13.jpg', 95.80),
('Hotel del Bosque', 'Conéctate con la naturaleza en nuestro hotel rodeado de bosques', 'src/assets/img/foto14.jpg', 130.75),
('Villa Elegante', 'Una villa elegante para una estancia lujosa', 'src/assets/img/foto15.jpg', 185.25),
('Hostal Bohemio', 'Vive la bohemia en nuestro acogedor hostal', 'src/assets/img/foto16.jpg', 55.00),
('Residencia de Playa', 'Relájate junto al mar en nuestra residencia costera', 'src/assets/img/foto17.jpg', 160.90),
('Hotel de Montaña', 'Escapa a las alturas en nuestro hotel de montaña', 'src/assets/img/foto18.jpg', 110.50),
('Aparthotel Moderno', 'Comodidad y estilo se encuentran en nuestro aparthotel', 'src/assets/img/foto19.jpg', 95.00),
('Refugio Campestre', 'Encuentra la serenidad en nuestro refugio en pleno campo', 'src/assets/img/foto20.jpg', 120.00),
('Hotel Marítimo', 'Disfruta de la brisa marina en nuestro hotel junto a la playa', 'src/assets/img/foto21.jpg', 155.00),
('Cabañas del Bosque', 'Retiro acogedor en nuestras cabañas rodeadas de naturaleza', 'src/assets/img/foto22.jpg', 85.50),
('Suite Estelar', 'Una suite de ensueño con vistas panorámicas al cielo nocturno', 'src/assets/img/foto23.jpg', 200.00),
('Hostería Tradicional', 'Sumérgete en la cultura local en nuestra hostería tradicional', 'src/assets/img/foto24.jpg', 120.75),
('Hotel de Ensueño', 'Vive una experiencia única en nuestro hotel de ensueño', 'src/assets/img/foto25.jpg', 175.25),
('Alojamiento Boho', 'Vibra con el espíritu bohemio en nuestro alojamiento único', 'src/assets/img/foto26.jpg', 65.00),
('Villa del Lago', 'Relájate junto al lago en nuestra villa tranquila', 'src/assets/img/foto27.jpg', 145.90),
('Posada Serena', 'Un lugar sereno para descansar y recargar energías', 'src/assets/img/foto28.jpg', 105.50),
('Hotel Boutique Arte', 'Descubre el arte y la elegancia en nuestro hotel boutique', 'src/assets/img/foto29.jpg', 135.00),
('Resort Esmeralda', 'Sumérgete en el lujo y la belleza en nuestro resort exclusivo', 'src/assets/img/foto30.jpg', 250.00),
('Hotel Ecléctico', 'Una mezcla única de estilos en nuestro hotel ecléctico', 'src/assets/img/foto31.jpg', 110.00),
('Alojamiento Zen', 'Encuentra la paz y la armonía en nuestro alojamiento zen', 'src/assets/img/foto32.jpg', 95.75),
('Villa Aurora', 'Experimenta la belleza del amanecer en nuestra villa junto al mar', 'src/assets/img/foto33.jpg', 180.50),
('Posada del Valle', 'Descubre la belleza natural en nuestra posada en el valle', 'src/assets/img/foto34.jpg', 125.25),
('Residencia Artística', 'Sumérgete en la creatividad en nuestra residencia para artistas', 'src/assets/img/foto35.jpg', 150.00),
('Hostal Colorido', 'Vibrantes colores y comodidad en nuestro acogedor hostal', 'src/assets/img/foto36.jpg', 70.90),
('Casa de Campo', 'Un retiro rural en nuestra encantadora casa de campo', 'src/assets/img/foto37.jpg', 100.50),
('Hotel Mirador', 'Vistas impresionantes desde nuestro hotel en la colina', 'src/assets/img/foto38.jpg', 135.00),
('Cabañas del Mar', 'Relájate en nuestras cabañas con vista al océano', 'src/assets/img/foto39.jpg', 155.75),
('Hotel Histórico', 'Sumérgete en la historia en nuestro hotel lleno de encanto', 'src/assets/img/foto40.jpg', 120.00),
('Hotel Tropical', 'Sumérgete en el paraíso tropical en nuestro exclusivo hotel', 'src/assets/img/foto41.jpg', 200.00),
('Casa de Playa', 'Una acogedora casa junto al mar para unas vacaciones perfectas', 'src/assets/img/foto42.jpg', 120.50),
('Hostería del Bosque', 'Disfruta de la naturaleza en nuestra encantadora hostería', 'src/assets/img/foto1.jpg', 95.25),
('Alojamiento Familiar', 'Un lugar acogedor para toda la familia', 'src/assets/img/foto2.jpg', 150.00),
('Hotel Serenity', 'Encuentra serenidad y confort en nuestro elegante hotel', 'src/assets/img/foto3.jpg', 180.75),
('Cabañas del Amanecer', 'Disfruta de impresionantes amaneceres desde nuestras cabañas', 'src/assets/img/foto4.jpg', 90.50),
('Resort Harmony', 'Vive en armonía con la naturaleza en nuestro resort exclusivo', 'src/assets/img/foto5.jpg', 220.00),
('Posada del Marino', 'Una posada encantadora para los amantes del mar', 'src/assets/img/foto6.jpg', 130.25),
('Hotel Aurora Boreal', 'Observa la maravilla natural de las luces del norte desde nuestro hotel', 'src/assets/img/foto7.jpg', 250.50),
('Hostal Tranquilo', 'Descansa en paz y tranquilidad en nuestro acogedor hostal', 'src/assets/img/foto8.jpg', 80.00),
('Hotel Moderno', 'Un hotel con un toque moderno y elegante para tu estancia', 'src/assets/img/foto9.jpg', 160.00),
('Casa Tranquila', 'Encuentra la paz y la tranquilidad en nuestra acogedora casa', 'src/assets/img/foto10.jpg', 110.50),
('Hostería del Valle', 'Disfruta de la naturaleza en nuestra encantadora hostería en el valle', 'src/assets/img/foto11.jpg', 85.25),
('Alojamiento Sereno', 'Un lugar sereno para tu descanso y relajación', 'src/assets/img/foto12.jpg', 120.00),
('Hotel Vista Panorámica', 'Vistas impresionantes desde nuestro hotel en lo alto', 'src/assets/img/foto13.jpg', 195.75),
('Cabañas del Atardecer', 'Disfruta de hermosos atardeceres desde nuestras cabañas acogedoras', 'src/assets/img/foto14.jpg', 100.50),
('Resort Elegante', 'Vive la elegancia y el lujo en nuestro exclusivo resort', 'src/assets/img/foto15.jpg', 240.00),
('Posada del Viajero', 'Una posada encantadora para los amantes de los viajes', 'src/assets/img/foto16.jpg', 135.25),
('Hotel Estilo Urbano', 'Experimenta la vida urbana en nuestro moderno hotel en la ciudad', 'src/assets/img/foto17.jpg', 180.50),
('Hostal Acogedor', 'Encuentra comodidad y calidez en nuestro acogedor hostal', 'src/assets/img/foto18.jpg', 75.00),
('Hotel Bella Vista', 'Vive la belleza con impresionantes vistas panorámicas', 'src/assets/img/foto19.jpg', 155.00),
('Casa Rural Encanto de la Sierra', 'Una casa rural encantadora en plena naturaleza', 'src/assets/img/foto20.jpg', 95.50),
('Hostería del Bosque', 'Descubre la tranquilidad en nuestra hostería rodeada de bosques', 'src/assets/img/foto21.jpg', 120.25),
('Alojamiento Sereno', 'Un refugio sereno para tu descanso y relajación', 'src/assets/img/foto22.jpg', 130.00),
('Hotel Vista del Mar', 'Disfruta de las impresionantes vistas al mar desde nuestro hotel', 'src/assets/img/foto23.jpg', 185.75),
('Cabañas del Lago', 'Relájate junto al lago en nuestras acogedoras cabañas', 'src/assets/img/foto24.jpg', 110.50),
('Resort Costa Serena', 'Vive la serenidad y el lujo en nuestro exclusivo resort', 'src/assets/img/foto25.jpg', 220.00),
('Posada del Viajero', 'Una posada encantadora para los amantes de los viajes', 'src/assets/img/foto26.jpg', 135.25),
('Hotel Ciudadano', 'Experimenta la vida urbana en nuestro moderno hotel en el corazón de la ciudad', 'src/assets/img/foto27.jpg', 198.50),
('Hostal del Pueblo', 'Encuentra comodidad y calidez en nuestro acogedor hostal en el pintoresco pueblo', 'src/assets/img/foto28.jpg', 80.00),
('Hotel Paris Encanto', 'Disfruta del encanto parisino en nuestro elegante hotel', 'src/assets/img/foto29.jpg', 220.00),
('Hostal Roma Céntrico', 'Experimenta el corazón de Roma en nuestro céntrico hostal', 'src/assets/img/foto30.jpg', 180.50),
('Resort Barcelona Playa', 'Relájate en la playa de Barcelona en nuestro lujoso resort', 'src/assets/img/foto31.jpg', 260.75),
('Casa Kyoto Tradicional', 'Sumérgete en la tradición japonesa en nuestra casa en Kyoto', 'src/assets/img/foto32.jpg', 195.00),
('Hotel Tranquilidad', 'Relájate y disfruta de la serenidad en nuestro acogedor hotel', 'src/assets/img/foto33.jpg', 120.00),
('Alojamiento Montaña Vista', 'Increíbles vistas a la montaña desde nuestro acogedor alojamiento', 'src/assets/img/foto34.jpg', 85.75),
('Hostería Campestre', 'Hospitalidad y naturaleza se encuentran en nuestra hostería', 'src/assets/img/foto35.jpg', 110.25),
('Casa Rural Encanto Natural', 'Descubre el encanto natural en nuestra acogedora casa rural', 'src/assets/img/foto36.jpg', 95.00),
('Hotel Marítimo', 'Vive la experiencia marítima en nuestro encantador hotel', 'src/assets/img/foto37.jpg', 160.50),
('Cabañas del Bosque', 'Sumérgete en la tranquilidad de nuestro bosque en nuestras cabañas', 'src/assets/img/foto38.jpg', 125.00),
('Hotel de las Estrellas', 'Descubre el lujo bajo el cielo estrellado en nuestro hotel en Barcelona', 'src/assets/img/foto40.jpg', 195.00),
('Residencial Bohemia', 'Sumérgete en la bohemia y encanto de Praga en nuestra residencial', 'src/assets/img/foto41.jpg', 170.50),
('Alojamiento Histórico', 'Viaja en el tiempo en nuestro alojamiento histórico en Roma', 'src/assets/img/foto42.jpg', 240.75),
('Suite Elegante', 'Disfruta de la elegancia en cada rincón de nuestra suite en Milán', 'src/assets/img/foto1.jpg', 215.00),
('Refugio de la Montaña', 'Escápate a la serenidad de la montaña en nuestro refugio en Interlaken', 'src/assets/img/foto2.jpg', 185.50),
('Casa del Arte Moderno', 'Vive la modernidad y arte en nuestra casa en Viena', 'src/assets/img/foto3.jpg', 200.25),
('Hotel de Ensueño', 'Haz realidad tus sueños en nuestro hotel en Ámsterdam', 'src/assets/img/foto4.jpg', 175.00),
('Alojamiento del Canal', 'Descubre la belleza junto al canal en nuestro alojamiento en Bruselas', 'src/assets/img/foto5.jpg', 160.75),
('Cabañas Acogedoras', 'Sumérgete en la acogedora atmósfera de nuestras cabañas en Zurich', 'src/assets/img/foto6.jpg', 145.00),
('Hotel Resplandor', 'Brilla con nosotros en el resplandor de nuestro hotel en Luxemburgo', 'src/assets/img/foto7.jpg', 180.25);